-- MBC MESSAGING & BROADCAST INFRASTRUCTURE UPGRADE
-- RUN THIS IN SUPABASE SQL EDITOR

-- 1. UPGRADE MESSAGES TABLE FOR EDIT/DELETE AUDIT
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS edited BOOLEAN DEFAULT FALSE;
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS edited_at TIMESTAMPTZ;
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

-- 2. UPGRADE BROADCASTS TABLE FOR PRIORITY INDEXING
ALTER TABLE public.broadcasts ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'info';

-- 3. ENSURE BROADCASTS RLS IS ACCESSIBLE
ALTER TABLE public.broadcasts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for broadcasts" ON public.broadcasts;
CREATE POLICY "Enable all access for broadcasts" ON public.broadcasts FOR ALL USING (true);
